application:
  location: config (GitHub)
  config:
    profile: prod
    description: valor obtenido desde 'exchangerate-prod.yml'

spring:
  data:
    mongodb:
      uri: mongodb+srv://aromeroh:q8Kf4Ppp@cluster0.0gini.mongodb.net/exchangerate?retryWrites=true&w=majority

logging:
  level:
    root: info
